name = "Carottes à la poêle"
cooking_time = 15
unnecessary_ingredients = []
necessary_ingredients = [
    "carotte",
    "huile",
    "oignons",
]
tags = [
    "sain",
]
recipe = "Faire cuire les carottes coupées avec les oigons et l'huile dans une poêle"
description = ""
mark = 5
added_date = "2026-09-26"
