name = "Goujère"
cooking_time = 45
unnecessary_ingredients = []
necessary_ingredients = [
    "farine",
    "oeuf",
    "gruyère râpé",
]
tags = []
recipe = "|https://www.marmiton.org/recettes/recette_gougeres-faciles_13241.aspx|la recette sur marmiton|"
description = "Un tres bon plat"
mark = 10
added_date = "2026-09-13"
