name = "pates à sauce tomate"
cooking_time = 15
unnecessary_ingredients = [
    "bonjour",
]
necessary_ingredients = [
    "Sauce tomate",
    "Pate",
]
tags = [
    "italien",
    "pate",
    "sain",
]
recipe = "Fais ça, puis ça et ça"
description = ""
mark = 8
added_date = "2026-08-09"
