name = "pates à sauce tomate"
cooking_time = 5
unnecessary_ingredients = []
necessary_ingredients = [
    "pâtes",
    "sauce tomate",
]
tags = [
    "italien",
    "pâte",
]
recipe = "Faire cuire les pâtes.\nEgouter les pâtes.\nMettre la sauce tomate et mélanger.\nAssaisonner et servir."
description = "Simplement des pâtes avec de la sauce tomate."
mark = 8
added_date = "2026-08-09"
