name = "pates carbonara"
cooking_time = 10
unnecessary_ingredients = [
    "huile d'olive",
    "crème",
]
necessary_ingredients = [
    "oeufs",
    "pâtes",
    "lardon",
    "parmesan",
]
tags = [
    "italien",
    "pâte",
]
recipe = "Faire cuire des lardons dans une poile.\nFaire cuire les pâtes dans de l'eau chaude.\nDans un bol, melangé le jaune d'oeuf et le parmesan (on peut y rajouter une touche d'huile d'olive)\nMélanger tout dans la csserolle et servir."
description = "Des pates aves des oeufs et des lardons."
mark = 9
added_date = "2026-08-09"
