#le nom du plat
name = "pates à sauce tomate"

#la date d'ajout du plat: Year-Month-Day
added_date = "2026-08-09" 

# le temp de presentation en minute, -1 si inconnue
cooking_time = 15

#les ingrédients reellement necessaire
necessary_ingredients = ["Sauce tomate","Pate"]

# la liste entiere des autres ingrédients
unnecessary_ingredients = []

tags = ["italien","pate","sain"]

recipe = "Fais ça, puis ça et ça"

description = "Des pates aves de la sauce tomate."

#une note sur 10, -1 si inconnue
mark = 8