name = "Soupe de légume"
cooking_time = 30
unnecessary_ingredients = []
necessary_ingredients = [
    "poireau",
    "pomme de terre",
    "carotte",
    "panais",
    "tomate",
]
tags = [
    "soupe",
    "liquide",
    "sain",
]
recipe = "Couper les légumes en morceau.\nLes faire boullir à petit feu.\nPasser les légume au moulin et rajouter l'eau du bouillon."
description = "C'est juste une soupe au légume."
mark = 8
added_date = "2026-08-09"
