name = "Tartiflette"
cooking_time = 75
unnecessary_ingredients = []
necessary_ingredients = [
    "reblochon",
    "pomme de terre",
    "lardon",
    "oignon",
    "ails",
]
tags = [
    "fromage",
    "four",
]
recipe = "|https://www.marmiton.org/recettes/recette_la-vraie-tartiflette_17634.aspx| recette sur marmiton|"
description = ""
mark = 10
added_date = "2026-09-26"
